In [1]:
import numpy as np
import pandas as pd

# Numpy Array Operations

## Create a 1D NumPy Array

In [2]:
temperatures_w1=np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

## Inspection and Properties

In [4]:
#Shape

temperatures_w1.shape

(7,)

In [5]:
#Data type

temperatures_w1.dtype

dtype('float64')

In [6]:
#Number of elements

temperatures_w1.size

7

## Array Operations

In [7]:
#Convert Celsius into Fahrenheit

Fahrenheit = (temperatures_w1 * 9/5) + 32
Fahrenheit

array([72.5 , 77.54, 69.44, 74.12, 78.98, 76.64, 71.42])

In [8]:
#Maximum temperature

np.max(temperatures_w1)

np.float64(26.1)

In [9]:
#Minimum temperature

np.min(temperatures_w1)

np.float64(20.8)

In [10]:
#Average temperature

np.mean(temperatures_w1)

np.float64(23.542857142857144)

## Array Slicing and Indexing

In [12]:
#First three days

temperatures_w1[0:3]

array([22.5, 25.3, 20.8])

In [13]:
#Weekend (last two days)

temperatures_w1[-2:]

array([24.8, 21.9])

In [14]:
#Middle three days

temperatures_w1[2:5]

array([20.8, 23.4, 26.1])

## Create a 2D Array

In [16]:
temperatures=np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

## Inspect and Slice the 2D Array

In [17]:
#Shape

temperatures.shape

(2, 7)

In [18]:
#Data type

temperatures.dtype

dtype('float64')

In [19]:
#Total number of elements

temperatures.size

14

In [20]:
#Extract Week 1

temperatures[0]

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [21]:
#Extract Week 2

temperatures[-1]

array([19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1])

In [24]:
#Extract weekends for both weeks

temperatures[:,-2:]

array([[24.8, 21.9],
       [22.8, 20.1]])

# Pandas Series

## Creating a Pandas Series

In [25]:
marks=pd.Series([95, 92, 89, 85, 80],index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'])
marks

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

## Indexing and Slicing

In [40]:
#Access the 1st rank using integer index position

print(marks.iloc[[0]])

Rank1    95
dtype: int64

In [31]:
#Retrieve top 3 ranks using loc

marks.loc[['Rank1','Rank2','Rank3']]

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [41]:
#Retrieve the 3rd rank using iloc

print(marks.iloc[[2]])

Rank3    89
dtype: int64

In [34]:
#Boolean masking – Marks greater than 90

marks[marks>90]

Rank1    95
Rank2    92
dtype: int64

## Manipulating Series

In [42]:
#Modify the 1st rank mark to 100

marks.iloc[0]=100
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [47]:
# Remove the last rank

marks=marks.drop('Rank5')
marks

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [48]:
#Calculate CGPA by dividing each mark by 10

CGPA=marks/10
CGPA

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

# Pandas DataFrame

## Creating a DataFrame

In [50]:
Dict = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],

    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],

    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
}
print(Dict)

{'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110], 'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'], 'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South', 'North'], 'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]}

In [52]:
transactions=pd.DataFrame(Dict)
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

## Data Exploration

In [53]:
#Display the DataFrame

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [54]:
#Display the first 5 rows using head()

transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [55]:
#Display the last 5 rows using tail()

transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [56]:
#Check the shape

transactions.shape

(10, 4)

In [57]:
#Display column names

transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='str')

In [58]:
#Check data types

transactions.dtypes

TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [59]:
#Get complete basic information

transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     str
 2   Region           10 non-null     str
 3   Amount           10 non-null     int64
dtypes: int64(2), str(2)
memory usage: 593.0 bytes

In [62]:
#Display only ProductCategory and Amount

transactions[['ProductCategory','Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [63]:
#Retrieve the last 3 columns using iloc

transactions.iloc[:,-3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [66]:
#Filter rows where Region is North and Amount is greater than 200

transactions[(transactions['Region']=='North')&(transactions['Amount']>200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [67]:
#Find value counts for ProductCategory

transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [68]:
#Find unique values in Region

transactions['Region'].unique()

<ArrowStringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [69]:
#Group by Region and calculate mean Amount

transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

## Manipulating the DataFrame

In [70]:
#Modify Amount for TransactionID 102 to 165

transactions.loc[transactions['TransactionID']==102,'Amount']=165
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [71]:
#Add a new column Discount by calculating 10% of Amount

transactions['Discount']=transactions['Amount']*0.1
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [72]:
#Remove the row with TransactionID 109

transactions=transactions.drop(transactions[transactions['TransactionID'] == 109].index)
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [74]:
#Delete the Discount column

transactions=transactions.drop(['Discount'],axis=1)
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400